name: Build and Push Docker Images
concurrency:
  group: build-and-push
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          username: yanhao98
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          context: .
          pull: true
          push: ${{ github.event_name != 'pull_request' && github.actor != 'nektos/act' }}
          tags: yanhao98/jupyter-vnpy:latest
          platforms: linux/amd64
